import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import weekOfYear from "dayjs/plugin/weekOfYear";
import "./globals.css";
import dayjs from "dayjs";

dayjs.extend(weekOfYear);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Racer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "dark")}>{children}</body>
    </html>
  );
}
