export const NOVICE_2_TRAINING_PLAN = {
  title: "Novice 2 Marathon Training Program",
  slug: "halhigdon-novice-2-marathon",
  activities: [
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 1,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 1,
    },
    {
      day: 3,
      details: "5 m pace",
      type: "run",
      week: 1,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 1,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 1,
    },
    {
      day: 6,
      details: "8 mi run",
      type: "run",
      week: 1,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 1,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 2,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 2,
    },
    {
      day: 3,
      details: "5 mi run",
      type: "run",
      week: 2,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 2,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 2,
    },
    {
      day: 6,
      details: "9 mi run",
      type: "run",
      week: 2,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 2,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 3,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 3,
    },
    {
      day: 3,
      details: "5 m pace",
      type: "run",
      week: 3,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 3,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 3,
    },
    {
      day: 6,
      details: "6 mi run",
      type: "run",
      week: 3,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 3,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 4,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 4,
    },
    {
      day: 3,
      details: "6 m pace",
      type: "run",
      week: 4,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 4,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 4,
    },
    {
      day: 6,
      details: "11 mi run",
      type: "run",
      week: 4,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 4,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 5,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 5,
    },
    {
      day: 3,
      details: "6 mi run",
      type: "run",
      week: 5,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 5,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 5,
    },
    {
      day: 6,
      details: "12 mi run",
      type: "run",
      week: 5,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 5,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 6,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 6,
    },
    {
      day: 3,
      details: "6 m pace",
      type: "run",
      week: 6,
    },
    {
      day: 4,
      details: "3 mi run",
      type: "run",
      week: 6,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 6,
    },
    {
      day: 6,
      details: "9 mi run",
      type: "run",
      week: 6,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 6,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 7,
    },
    {
      day: 2,
      details: "4 mi run",
      type: "run",
      week: 7,
    },
    {
      day: 3,
      details: "7 m pace",
      type: "run",
      week: 7,
    },
    {
      day: 4,
      details: "4 mi run",
      type: "run",
      week: 7,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 7,
    },
    {
      day: 6,
      details: "14 mi run",
      type: "run",
      week: 7,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 7,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 8,
    },
    {
      day: 2,
      details: "4 mi run",
      type: "run",
      week: 8,
    },
    {
      day: 3,
      details: "7 mi run",
      type: "run",
      week: 8,
    },
    {
      day: 4,
      details: "4 mi run",
      type: "run",
      week: 8,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 8,
    },
    {
      day: 6,
      details: "15 mi run",
      type: "run",
      week: 8,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 8,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 9,
    },
    {
      day: 2,
      details: "4 mi run",
      type: "run",
      week: 9,
    },
    {
      day: 3,
      details: "7 m pace",
      type: "run",
      week: 9,
    },
    {
      day: 4,
      details: "4 mi run",
      type: "run",
      week: 9,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 9,
    },
    {
      day: 6,
      details: "Rest",
      type: "rest",
      week: 9,
    },
    {
      day: 0,
      details: "Half Marathon",
      type: "cross",
      week: 9,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 10,
    },
    {
      day: 2,
      details: "4 mi run",
      type: "run",
      week: 10,
    },
    {
      day: 3,
      details: "8 m pace",
      type: "run",
      week: 10,
    },
    {
      day: 4,
      details: "4 mi run",
      type: "run",
      week: 10,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 10,
    },
    {
      day: 6,
      details: "17 mi run",
      type: "run",
      week: 10,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 10,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 11,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 11,
    },
    {
      day: 3,
      details: "8 mi run",
      type: "run",
      week: 11,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 11,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 11,
    },
    {
      day: 6,
      details: "18 mi run",
      type: "run",
      week: 11,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 11,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 12,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 12,
    },
    {
      day: 3,
      details: "8 m pace",
      type: "run",
      week: 12,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 12,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 12,
    },
    {
      day: 6,
      details: "13 mi run",
      type: "run",
      week: 12,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 12,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 13,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 13,
    },
    {
      day: 3,
      details: "5 m pace",
      type: "run",
      week: 13,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 13,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 13,
    },
    {
      day: 6,
      details: "19 mi run",
      type: "run",
      week: 13,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 13,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 14,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 14,
    },
    {
      day: 3,
      details: "8 mi run",
      type: "run",
      week: 14,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 14,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 14,
    },
    {
      day: 6,
      details: "12 mi run",
      type: "run",
      week: 14,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 14,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 15,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 15,
    },
    {
      day: 3,
      details: "5 m pace",
      type: "run",
      week: 15,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 15,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 15,
    },
    {
      day: 6,
      details: "20 mi run",
      type: "run",
      week: 15,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 15,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 16,
    },
    {
      day: 2,
      details: "5 mi run",
      type: "run",
      week: 16,
    },
    {
      day: 3,
      details: "4 m pace",
      type: "run",
      week: 16,
    },
    {
      day: 4,
      details: "5 mi run",
      type: "run",
      week: 16,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 16,
    },
    {
      day: 6,
      details: "12 mi run",
      type: "run",
      week: 16,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 16,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 17,
    },
    {
      day: 2,
      details: "4 mi run",
      type: "run",
      week: 17,
    },
    {
      day: 3,
      details: "3 mi run",
      type: "run",
      week: 17,
    },
    {
      day: 4,
      details: "4 mi run",
      type: "run",
      week: 17,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 17,
    },
    {
      day: 6,
      details: "8 mi run",
      type: "run",
      week: 17,
    },
    {
      day: 0,
      details: "Cross",
      type: "cross",
      week: 17,
    },
    {
      day: 1,
      details: "Rest",
      type: "rest",
      week: 18,
    },
    {
      day: 2,
      details: "3 mi run",
      type: "run",
      week: 18,
    },
    {
      day: 3,
      details: "2 mi run",
      type: "run",
      week: 18,
    },
    {
      day: 4,
      details: "Rest",
      type: "rest",
      week: 18,
    },
    {
      day: 5,
      details: "Rest",
      type: "rest",
      week: 18,
    },
    {
      day: 6,
      details: "2 mi run",
      type: "run",
      week: 18,
    },
    {
      day: 0,
      details: "Marathon",
      type: "cross",
      week: 18,
    },
  ],
};
